[tox]
envlist =
       {py310}-django{5.1}

[testenv]
#rsx = report all errors, -s = capture=no, -x = fail fast, --pdb for local testing http://www.linuxcertif.com/man/1/py.test/
commands = py.test -rsx -s -x
setenv =
       PYTHONDONTWRITEBYTECODE=1
deps =
       django5.1: Django==5.1.6
       pytest-django
       selenium==4.8.2
